AWSTemplateFormatVersion: "2010-09-09"
Description: IAD VPC Attachment for CloudWAN
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "VPC Parameters"
        Parameters:
         - CorenetworkID

Parameters:
  CorenetworkID:
    Description: "CorenetworkID"
    Type: String
    Default: "CorenetworkID"
  IADVPCBlueCloudWANSubnetAARN:
    Description: "IAD_VPC_Blue_CloudWANSubnetA_ARN"
    Type: String
    AllowedPattern: "arn:aws:ec2:*"
    Default: "IAD_VPC_Blue_CloudWANSubnetA_ARN" 
  IADVPCBlueCloudWANSubnetBARN:
    Description: "IAD_VPC_Blue_CloudWANSubnetB_ARN"
    Type: String
    AllowedPattern: "arn:aws:ec2:*"
    Default: "IAD_VPC_Blue_CloudWANSubnetB_ARN"
  IADVPCGreenCloudWANSubnetAARN:
    Description: "IAD_VPC_Green_CloudWANSubnetA_ARN"
    Type: String
    AllowedPattern: "arn:aws:ec2:*"
    Default: "IAD_VPC_Green_CloudWANSubnetA_ARN" 
  IADVPCGreenCloudWANSubnetBARN:
    Description: "IAD_VPC_Green_CloudWANSubnetB_ARN"
    Type: String
    AllowedPattern: "arn:aws:ec2:*"
    Default: "IAD_VPC_Green_CloudWANSubnetB_ARN"
  IADVPCBlueARN:
    Description: "IAD_VPC_Blue_ARN"
    Type: String
    AllowedPattern: "arn:aws:cloudformation:*"
    Default: "IAD_VPC_Blue_ARN"  
  IADVPCGreenARN:
    Description: "IAD_VPC_Blue_ARN"
    Type: String
    AllowedPattern: "arn:aws:cloudformation:*"
    Default: "IAD_VPC_Blue_ARN"  

Resources:
  IADBLUEVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId: !Ref CorenetworkID
      SubnetArns:
        - !Ref IADVPCBlueCloudWANSubnetAARN
        - !Ref IADVPCBlueCloudWANSubnetBARN
      Tags:
        - Key: segment
          Value: Blue
      VpcArn: !Ref IADVPCBlueARN

  IADGREENVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId: !Ref CorenetworkID
      SubnetArns:
        - !Ref IADVPCGreenCloudWANSubnetAARN
        - !Ref IADVPCGreenCloudWANSubnetBARN
      Tags:
        - Key: segment
          Value: Green
      VpcArn: !Ref IADVPCGreenARN
        