AWSTemplateFormatVersion: "2010-09-09"
Description: IAD VPC Attachment for CloudWAN
etadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "VPC Parameters"
        Parameters:
         - CorenetworkID

Parameters:
  CorenetworkID:
    Description: "CorenetworkID"
    Type: String
    Default: "CorenetworkID"

Resources:
  IADBLUEVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId:
        - Ref: CorenetworkID
      SubnetArns:
        - Fn::Join:
            - ""
            - - "arn:aws:ec2:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":subnet/"
              - Fn::ImportValue: IAD-VPC-Blue-CloudWANSubnetA
        - Fn::Join:
            - ""
            - - "arn:aws:ec2:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":subnet/"
              - Fn::ImportValue: IAD-VPC-Blue-CloudWANSubnetB
      Tags:
        - Key: segment
          Value: Blue
      VpcArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":vpc/"
            - Fn::ImportValue: IAD-VPC-Blue
  IADGREENVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId:
        - Ref: CorenetworkID
      SubnetArns:
        - Fn::Join:
            - ""
            - - "arn:aws:ec2:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":subnet/"
              - Fn::ImportValue: IAD-VPC-Green-CloudWANSubnetA
        - Fn::Join:
            - ""
            - - "arn:aws:ec2:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":subnet/"
              - Fn::ImportValue: IAD-VPC-Green-CloudWANSubnetB
      Tags:
        - Key: segment
          Value: Green
      VpcArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":vpc/"
            - Fn::ImportValue: IAD-VPC-Green