AWSTemplateFormatVersion: "2010-09-09"
Description: IAD VPC Attachment for CloudWAN
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "VPC Parameters"
        Parameters:
         - CorenetworkID

Parameters:
  CorenetworkID:
    Description: "CorenetworkID"
    Type: String
    Default: "CorenetworkID"
  IADVPCBlueCloudWANSubnetAARN:
    Description: "IAD_VPC_Blue_CloudWANSubnetA_ARN"
    Type: String
    Default: "IAD_VPC_Blue_CloudWANSubnetA_ARN" 
  IADVPCBlueCloudWANSubnetBARN:
    Description: "IAD_VPC_Blue_CloudWANSubnetB_ARN"
    Type: String
    Default: "IAD_VPC_Blue_CloudWANSubnetB_ARN"
  IADVPCGreenCloudWANSubnetAARN:
    Description: "IAD_VPC_Green_CloudWANSubnetA_ARN"
    Type: String
    Default: "IAD_VPC_Green_CloudWANSubnetA_ARN" 
  IADVPCGreenCloudWANSubnetBARN:
    Description: "IAD_VPC_Green_CloudWANSubnetB_ARN"
    Type: String
    Default: "IAD_VPC_Green_CloudWANSubnetB_ARN"
  IADVPCBlueARN:
    Description: "IAD_VPC_Blue_ARN"
    Type: String
    Default: "IAD_VPC_Blue_ARN"  
  IADVPCGreenARN:
    Description: "IAD_VPC_Blue_ARN"
    Type: String
    Default: "IAD_VPC_Blue_ARN"  
  IADVPCBlueCloudWANSubnetAID:
    Description: "IADVPCBlueCloudWANSubnetAID"
    Type: String
    Default: "IADVPCBlueCloudWANSubnetAID"
  IADVPCBlueCloudWANSubnetAID:
    Description: "IADVPCGreenCloudWANSubnetAID"
    Type: String
    Default: "IADVPCGreenCloudWANSubnetAID"
  IADVPCGreenCloudWANSubnetAID:
    Description: "IADVPCGreenCloudWANSubnetAID"
    Type: String
    Default: "IADVPCGreenCloudWANSubnetAID"
  IADVPCGreenCloudWANSubnetBID:
    Description: "IADVPCGreenCloudWANSubnetBID"
    Type: String
    Default: "IADVPCGreenCloudWANSubnetBID"    

Resources:
#  IADBLUEVPCAttachment:
#    Type: AWS::NetworkManager::VpcAttachment
#    Properties:
#      CoreNetworkId: !Ref CorenetworkID
#      SubnetArns:
#        - !Ref IADVPCBlueCloudWANSubnetAARN
#        - !Ref IADVPCBlueCloudWANSubnetBARN
#      Tags:
#        - Key: segment
#          Value: Blue
#      VpcArn: !Ref IADVPCBlueARN
#
#  IADGREENVPCAttachment:
#    Type: AWS::NetworkManager::VpcAttachment
#    Properties:
#      CoreNetworkId: !Ref CorenetworkID
#      SubnetArns:
#        - !Ref IADVPCGreenCloudWANSubnetAARN
#        - !Ref IADVPCGreenCloudWANSubnetBARN
#      Tags:
#        - Key: segment
#          Value: Green
#      VpcArn: !Ref IADVPCGreenARN

  IADBLUEVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId: !Ref CorenetworkID
      SubnetArns:
        - Fn::Join:
          - ""
          - - "arn:aws:ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AcountID
            - ":subnet/"
            - Ref: IADVPCBlueCloudWANSubnetAID
        - Fn::Join:
          - ""
          - - "arn:aws:ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AcountID
            - ":subnet/"
            - Ref: IADVPCBlueCloudWANSubnetBID
      Tags:
        - Key: segment
          Value: Blue
      VpcArn: !Ref IADVPCBlueARN

  IADGREENVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId: !Ref CorenetworkID
      SubnetArns:
        - Fn::Join:
          - ""
          - - "arn:aws:ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AcountID
            - ":subnet/"
            - Ref: IADVPCGreenCloudWANSubnetAID
        - Fn::Join:
          - ""
          - - "arn:aws:ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AcountID
            - ":subnet/"
            - Ref: IADVPCGreenCloudWANSubnetBID
      Tags:
        - Key: segment
          Value: Green
      VpcArn: !Ref IADVPCGreenARN    