AWSTemplateFormatVersion: "2010-09-09"
Description: IAD VPC Attachment for CloudWAN
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "VPC Parameters"
        Parameters:
         - CorenetworkID
         - IADVPCBlueCloudWANSubnetAARN
         - IADVPCBlueCloudWANSubnetBARN
         - IADVPCGreenCloudWANSubnetAARN
         - IADVPCGreenCloudWANSubnetBARN
#         - IADVPCBlueCloudWANSubnetAID
#         - IADVPCBlueCloudWANSubnetBID
#         - IADVPCGreenCloudWANSubnetAID
#         - IADVPCGreenCloudWANSubnetBID
         - IADVPCBlueID
         - IADVPCGreenID

Parameters:
  CorenetworkID:
    Description: "CorenetworkID"
    Type: String
    Default: "CorenetworkID"
  IADVPCBlueID:
    Description: "IADVPCBlueID"
    Type: String
    Default: "IADVPCBlueID"
  IADVPCGreenID:
    Description: "IADVPCGreenID"
    Type: String
    Default: "IADVPCGreenID"  
  IADVPCBlueCloudWANSubnetAARN:
    Description: "IAD_VPC_Blue_CloudWANSubnetA_ARN"
    Type: String
    Default: "IAD_VPC_Blue_CloudWANSubnetA_ARN" 
  IADVPCBlueCloudWANSubnetBARN:
    Description: "IAD_VPC_Blue_CloudWANSubnetB_ARN"
    Type: String
    Default: "IAD_VPC_Blue_CloudWANSubnetB_ARN"
  IADVPCGreenCloudWANSubnetAARN:
    Description: "IAD_VPC_Green_CloudWANSubnetA_ARN"
    Type: String
    Default: "IAD_VPC_Green_CloudWANSubnetA_ARN" 
  IADVPCGreenCloudWANSubnetBARN:
    Description: "IAD_VPC_Green_CloudWANSubnetB_ARN"
    Type: String
    Default: "IAD_VPC_Green_CloudWANSubnetB_ARN"
#  IADVPCBlueCloudWANSubnetAID:
#    Description: "IADVPCBlueCloudWANSubnetAID"
#    Type: String
#    Default: "IADVPCBlueCloudWANSubnetAID"
#  IADVPCBlueCloudWANSubnetBID:
#    Description: "IADVPCBlueCloudWANSubnetBID"
#    Type: String
#    Default: "IADVPCBlueCloudWANSubnetBID"
#  IADVPCGreenCloudWANSubnetAID:
#    Description: "IADVPCGreenCloudWANSubnetAID"
#    Type: String
#    Default: "IADVPCGreenCloudWANSubnetAID"
#  IADVPCGreenCloudWANSubnetBID:
#    Description: "IADVPCGreenCloudWANSubnetBID"
#    Type: String
#    Default: "IADVPCGreenCloudWANSubnetBID"    

Resources:
  IADBLUEVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId: 
        Ref: CorenetworkID
      SubnetArns:
        - Ref: IADVPCBlueCloudWANSubnetAARN
        - Ref: IADVPCBlueCloudWANSubnetBARN
      Tags:
        - Key: segment
          Value: Blue
      VpcArn: 
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":vpc/"
            - Ref: IADVPCBlueID

  IADGREENVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId: 
        Ref: CorenetworkID
      SubnetArns:
        - Ref: IADVPCGreenCloudWANSubnetAARN
        - Ref: IADVPCGreenCloudWANSubnetBARN
      Tags:
        - Key: segment
          Value: Green
      VpcArn: 
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":vpc/"
            - Ref: IADVPCGreenID

#  IADBLUEVPCAttachment:
#    Type: AWS::NetworkManager::VpcAttachment
#    Properties:
#      CoreNetworkId: 
#        Ref: CorenetworkID
#      SubnetArns:
#        - Fn::Join:
#          - ''
#          - - 'arn:aws:ec2:'
#            - Ref: "AWS::Region"
#            - ":"
#            - Ref: "AWS::AccountId"
#            - ':subnet/'
#            - Ref: IADVPCBlueCloudWANSubnetAID
#        - Fn::Join:
#          - ''
#          - - 'arn:aws:ec2:'
#            - Ref: "AWS::Region"
#            - ":"
#            - Ref: "AWS::AccountId"
#            - ':subnet/'
#            - Ref: IADVPCBlueCloudWANSubnetBID
#      Tags:
#        - Key: segment
#          Value: Blue
#      VpcArn: 
#        Fn::Join:
#          - ""
#          - - "arn:"
#            - Ref: AWS::Partition
#            - ":ec2:"
#            - Ref: AWS::Region
#            - ":"
#            - Ref: AWS::AccountId
#            - ":vpc/"
#            - Ref: IADVPCBlueID
#
#  IADGREENVPCAttachment:
#    Type: AWS::NetworkManager::VpcAttachment
#    Properties:
#      CoreNetworkId: 
#        Ref: CorenetworkID
#      SubnetArns:
#        - Fn::Join:
#          - ''
#          - - 'arn:aws:ec2:'
#            - Ref: "AWS::Region"
#            - ":"
#            - Ref: "AWS::AccountId"
#            - ':subnet/'
#            - Ref: IADVPCGreenCloudWANSubnetAID
#        - Fn::Join:
#          - ''
#          - - 'arn:aws:ec2:'
#            - Ref: "AWS::Region"
#            - ":"
#            - Ref: "AWS::AccountId"
#            - ':subnet/'
#            - Ref: IADVPCGreenCloudWANSubnetBID
#      Tags:
#        - Key: segment
#          Value: Green
#      VpcArn: 
#        Fn::Join:
#          - ""
#          - - "arn:"
#            - Ref: AWS::Partition
#            - ":ec2:"
#            - Ref: AWS::Region
#            - ":"
#            - Ref: AWS::AccountId
#            - ":vpc/"
#            - Ref: IADVPCGreenID
#