AWSTemplateFormatVersion: "2010-09-09"
Description: IAD VPC Attachment for CloudWAN
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "VPC Parameters"
        Parameters:
         - CorenetworkID

Parameters:
  CorenetworkID:
    Description: "CorenetworkID"
    Type: String
    Default: "CorenetworkID"
  IAD_VPC_Blue_CloudWANSubnetA_ARN:
    Description: "IAD_VPC_Blue_CloudWANSubnetA_ARN"
    Type: String
    Default: "IAD_VPC_Blue_CloudWANSubnetA_ARN" 
  IAD_VPC_Blue_CloudWANSubnetB_ARN:
    Description: "IAD_VPC_Blue_CloudWANSubnetB_ARN"
    Type: String
    Default: "IAD_VPC_Blue_CloudWANSubnetB_ARN"
  IAD_VPC_Green_CloudWANSubnetA_ARN:
    Description: "IAD_VPC_Green_CloudWANSubnetA_ARN"
    Type: String
    Default: "IAD_VPC_Green_CloudWANSubnetA_ARN" 
  IAD_VPC_Green_CloudWANSubnetB_ARN:
    Description: "IAD_VPC_Green_CloudWANSubnetB_ARN"
    Type: String
    Default: "IAD_VPC_Green_CloudWANSubnetB_ARN"
  IAD_VPC_Blue_ARN:
    Description: "IAD_VPC_Blue_ARN"
    Type: String
    Default: "IAD_VPC_Blue_ARN"  
  IAD_VPC_Green_ARN:
    Description: "IAD_VPC_Blue_ARN"
    Type: String
    Default: "IAD_VPC_Blue_ARN"  

Resources:
  IADBLUEVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId:
        - Ref: CorenetworkID
      SubnetArns:
        - Ref: IAD_VPC_Blue_CloudWANSubnetA_ARN
        - Ref: IAD_VPC_Blue_CloudWANSubnetB_ARN
      Tags:
        - Key: segment
          Value: Blue
      VpcArn:
        - Ref: IAD_VPC_Blue_ARN

  IADGREENVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId:
        - Ref: CorenetworkID
      SubnetArns:
        - Ref: IAD_VPC_Green_CloudWANSubnetA_ARN
        - Ref: IAD_VPC_Green_CloudWANSubnetB_ARN
      Tags:
        - Key: segment
          Value: Green
      VpcArn:
        - Ref: IAD_VPC_Green_ARN
        