AWSTemplateFormatVersion: "2010-09-09"
Description: "Add NRT Routing Table Update"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "VPC Parameters"
        Parameters:
         - DefaultRouteBlock
         - NRTBLUEBlock
         - NRTGREENBlock
         - SYDBLUEBlock
         - SYDGREENBlock
         - IADBLUEBlock
         - IADGREENBlock
         - PDXBLUEBlock
         - PDXGREENBlock
         - FRABLUEBlock
         - FRAGREENBlock
         - DUBBLUEBlock
         - DUBGREENBlock
Parameters:
  DefaultRouteBlock:
    Type: String
    Default: 0.0.0.0/0
    Description: "Enter desired CIDR to Default route"

  NRTBLUEBlock:
    Type: String
    Default: 10.21.0.0/16
    Description: "Enter desired CIDR to NRT VPC Blue route"

  NRTGREENBlock:
    Type: String
    Default: 10.22.0.0/16
    Description: "Enter desired CIDR to NRT VPC Green route"

  SYDBLUEBlock:
    Type: String
    Default: 10.121.0.0/16
    Description: "Enter desired CIDR to SYD VPC Blue route"

  SYDGREENBlock:
    Type: String
    Default: 10.122.0.0/16
    Description: "Enter desired CIDR to SYD VPC Green route"

  IADBLUEBlock:
    Type: String
    Default: 10.31.0.0/16
    Description: "Enter desired CIDR to IAD VPC Blue route"

  IADGREENBlock:
    Type: String
    Default: 10.32.0.0/16
    Description: "Enter desired CIDR to IAD VPC Green route"

  PDXBLUEBlock:
    Type: String
    Default: 10.131.0.0/16
    Description: "Enter desired CIDR to PDX VPC Blue route"

  PDXGREENBlock:
    Type: String
    Default: 10.132.0.0/16
    Description: "Enter desired CIDR to PDX VPC Green route"

  FRABLUEBlock:
    Type: String
    Default: 10.41.0.0/16
    Description: "Enter desired CIDR to FRA VPC Blue route"

  FRAGREENBlock:
    Type: String
    Default: 10.42.0.0/16
    Description: "Enter desired CIDR to FRA VPC Green route"

  DUBBLUEBlock:
    Type: String
    Default: 10.131.0.0/16
    Description: "Enter desired CIDR to DUB VPC Blue route"

  DUBGREENBlock:
    Type: String
    Default: 10.132.0.0/16
    Description: "Enter desired CIDR to DUB VPC Green route"

Resources:

### N2SVPC route table configuration

  SYDBlueAddRoute1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref SYDBLUEBlock
      CoreNetworkArn: arn:aws:networkmanager::632992457200:core-network/core-network-0383952fbf8ee2bac
      RouteTableId: 
        Fn::ImportValue: !Sub "NRT-VPC-Blue-PublicSubnetRouteTable"

  IADBlueAddRoute1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref IADBLUEBlock
      CoreNetworkArn: arn:aws:networkmanager::632992457200:core-network/core-network-0383952fbf8ee2bac
      RouteTableId: 
        Fn::ImportValue: !Sub "NRT-VPC-Blue-PublicSubnetRouteTable"

  PDXBlueAddRoute1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref PDXBLUEBlock
      CoreNetworkArn: arn:aws:networkmanager::632992457200:core-network/core-network-0383952fbf8ee2bac
      RouteTableId: 
        Fn::ImportValue: !Sub "NRT-VPC-Blue-PublicSubnetRouteTable"

  FRABlueAddRoute1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref FRABLUEBlock
      CoreNetworkArn: arn:aws:networkmanager::632992457200:core-network/core-network-0383952fbf8ee2bac
      RouteTableId: 
        Fn::ImportValue: !Sub "NRT-VPC-Blue-PublicSubnetRouteTable"

  DUBBlueAddRoute1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref DUBBLUEBlock
      CoreNetworkArn: arn:aws:networkmanager::632992457200:core-network/core-network-0383952fbf8ee2bac
      RouteTableId: 
        Fn::ImportValue: !Sub "NRT-VPC-Blue-PublicSubnetRouteTable"
