AWSTemplateFormatVersion: "2010-09-09"
Description: SYD VPC Attachment for CloudWAN
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "VPC Parameters"
        Parameters:
         - CorenetworkID
         - SYDVPCBlueCloudWANSubnetAARN
         - SYDVPCBlueCloudWANSubnetBARN
         - SYDVPCGreenCloudWANSubnetAARN
         - SYDVPCGreenCloudWANSubnetBARN
         - SYDVPCBlueID
         - SYDVPCGreenID

Parameters:
  CorenetworkID:
    Description: "CorenetworkID"
    Type: String
    Default: "CorenetworkID"
  SYDVPCBlueID:
    Description: "SYDVPCBlueID"
    Type: String
    Default: "SYDVPCBlueID"
  SYDVPCGreenID:
    Description: "SYDVPCGreenID"
    Type: String
    Default: "SYDVPCGreenID"  
  SYDVPCBlueCloudWANSubnetAARN:
    Description: "SYD_VPC_Blue_CloudWANSubnetA_ARN"
    Type: String
    Default: "SYD_VPC_Blue_CloudWANSubnetA_ARN" 
  SYDVPCBlueCloudWANSubnetBARN:
    Description: "SYD_VPC_Blue_CloudWANSubnetB_ARN"
    Type: String
    Default: "SYD_VPC_Blue_CloudWANSubnetB_ARN"
  SYDVPCGreenCloudWANSubnetAARN:
    Description: "SYD_VPC_Green_CloudWANSubnetA_ARN"
    Type: String
    Default: "SYD_VPC_Green_CloudWANSubnetA_ARN" 
  SYDVPCGreenCloudWANSubnetBARN:
    Description: "SYD_VPC_Green_CloudWANSubnetB_ARN"
    Type: String
    Default: "SYD_VPC_Green_CloudWANSubnetB_ARN"

Resources:
  SYDBLUEVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId: 
        Ref: CorenetworkID
      SubnetArns:
        - Ref: SYDVPCBlueCloudWANSubnetAARN
        - Ref: SYDVPCBlueCloudWANSubnetBARN
      Tags:
        - Key: segment
          Value: Blue
      VpcArn: 
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":vpc/"
            - Ref: SYDVPCBlueID

  SYDGREENVPCAttachment:
    Type: AWS::NetworkManager::VpcAttachment
    Properties:
      CoreNetworkId: 
        Ref: CorenetworkID
      SubnetArns:
        - Ref: SYDVPCGreenCloudWANSubnetAARN
        - Ref: SYDVPCGreenCloudWANSubnetBARN
      Tags:
        - Key: segment
          Value: Green
      VpcArn: 
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":ec2:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":vpc/"
            - Ref: SYDVPCGreenID